### ISSUE TITLE
Roadmap per la versione 1.0.0

### ISSUE THREAD

**Issue by dag7dev** [dag7dev/MozItaReBot#1]
## Che cos'è
Questo issue è riepilogativo e serve ad avere un quadro generale della situazione affinché il rilascio della versione 0.0.1 avvenga nel migliore dei modi.

## Cose importanti da sapere e leggere

**Come fare un commit in maniera efficiente**: https://www.conventionalcommits.org/en/v1.0.0/#summary

<details>
	<summary> <b>Come contribuire nella repo (modus operandi)</b></summary>

1. Prenotarsi nella issue: scrivere nei commenti di ogni issue della quale volete occuparvi (o fatemelo semplicemente sapere) e vi assegno il task in questione. Se potete assegnarvelo da soli, va benissimo così, meglio.

2. Lavorare **su un branch separato** con un nome significativo (es. se il comando è `/help` un nome del branch potrebbe essere `help-cmd`)

3. A stato abbastanza maturo della funzionalità, aprire una PR sul branch main. Se avete bisogno di cambiare qualcosa, basta segnarla come `draft`.
</details>

<details>
	<summary> <b>Codestyle, commenti, codice</b></summary>
Siamo fan della pulizia e vorremmo non scrivere il codice sorgente, o ricevere tra dieci anni chiamate su "quel dì di maggio che implementammo x funzionalità".

[TLDR;](https://data-flair.training/blogs/python-best-practices/)
</details>

<details>
	<summary> <b>Come stanno attualmente le cose</b></summary>
Dare un'occhiata all'attuale MozItaBot su Telegram per rendersi conto delle funzionalità e di cosa fanno i vari comandi.

I dati di [mozitaantispam_bot](https://github.com/MozillaItalia/mozitahub_bot)  sono gestiti tramite `json` : liste admin, e quant'altro sono nel file `liste.json`. **Tutti**  i messaggi del bot sono salvati in [`frasi.json`](https://raw.githubusercontent.com/MozillaItalia/mozitahub_bot/master/frasi.json). nella cartella `json` del bot, incluso il testo dei bottoni. Quelle stringhe dovrebbero essere usate anziché i messaggi nel sorgente.

Se pensate sia il caso di scorporare o rinominare file, decidiamo prima di cominciare a sviluppare.
</details>

## Comandi base
- [x] #2
- [x] #3
- [x] #4

## Comandi relativi ai gruppi
Riguardano un gruppo specifico. Tipicamente strutturati come <messaggio_descrizione> + <bottone_link_gruppo> + <bottone_back>. #5 
- [x] /home
- [x] /developers (o /sviluppo)
- [x] /dem
- [x] /l10n
- [x] /news: non è un gruppo, ma fa sempre la stessa cosa. Il bottone rimanda al canale news.

## Comandi di informazione generale
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10 -> https://github.com/dag7dev/MozItaReBot/issues/10#issuecomment-1289570106
- [x] #27

# Comandi deprecati
### Comandi "meeting"
- [X] /meeting: avere informazioni sui meeting video mensili comunitari. Stringa + data dell'ipotetico prossimo meeting + bottone "vai al canale youtube"
- [X] /prossimoMeeting
Per me non servono, l'attività non è grande e c'è il canale Telegram se vogliamo annunciare grandi call. Per tutto il resto c'è Home.

### Comandi minori vademecum
- [X] /vademecumGenerale
- [X] /vademecumTecnico
Non credo che nessuno mai verrà a digitare comandi del genere...

### Comandi admin - non prioritari
- [x] /admin: (solo per admin) gestire alcune impostazioni del bot.
Tutti questi comandi andrebbero deprecati. Non abbiamo niente da gestire in quanto il bot è un "bot vetrina".
### Comandi "avvisi"
- [x] /avvisi: vedere lo stato attuale degli avvisi, per attivarli o per disattivarli.
- [x] /avvisiOn: scorciatoia rapida per attivare gli avvisi.
- [x] /avvisiOff: scorciatoia rapida per disattivare gli avvisi.
Deprecherei anche queste funzioni in quanto non sono più utili (esiste il canale e al limite il gruppo Home).

**Comment by Mte90** [comment]
Domanda perchè leggendo https://github.com/MozillaItalia/mozitahub_bot/issues/51 non mi è chiaro perchè non vedo un file env di esempio tipo `.env-example`.

Altra questione il readme di questo progetto menziona antispam bot ma da quello che vedo invece è hub. State valutando una fusione dei due?

**Comment by dag7dev** [comment]
> non vedo un file env di esempio tipo .env-example.
è stato dimenticato nella fretta

> progetto menziona antispam bot ma da quello che vedo invece è hub
fixato, era solo un nome errato

**Comment by dag7dev** [comment]
Ciao a tutti. Siamo a un buon punto, mancano pochissimi comandi per la 0.1.

Riguardo i test: non ho chiuso la issue, ma nulla vieta eventualmente di aggiungere più test.

Chiedo a @Mte90 @Trafitto e @lorenzocamilli di esprimere cosa pensano riguardo i comandi deprecati.
Ho deciso deliberatamente di deprecare quei comandi attualmente presenti sul bot, volevo conoscere la vostra opinione.

**Comment by Trafitto** [comment]
Hai fatto bene a non chiudere la issue, io ne ho aggiunti solo alcuni il piú é stato trovare una libreria funzionante che mockasse il bot di Telegram, se avete qualche suggerimento per qualche test ma non potete aggiungerli in prima persona pingatemi che a me fa sempre piacere scrivere un test

**Comment by lorenzocamilli** [comment]
Riguardo i comandi deprecati, a quanto mi risulta i meeting non si fanno più settimanalmente, quindi direi che si possono rimuove entrambi i comandi, siccome eventuali meeting vengono comunicati anche nel gruppo home si saprà da lì quando (e se) ci saranno.

**Comment by lorenzocamilli** [comment]
Con @dag7dev avevamo parlanto anche di altre cose che non ci convincevano, una che ricordo è il comando "regolamento", se ne parla [qui](https://github.com/dag7dev/MozItaReBot/issues/9#issuecomment-1062222017) e forse anche vedemecum. Cosa ne pensate?

**Comment by Mte90** [comment]
Sono d'accordo per rimuovere meeting, possiamo sempre erimplementarlo quando si faranno nuovamente, per il resto ho risposto nei due ticket :-)

**Comment by lorenzocamilli** [comment]
Per quanto riguarda il comando "vademecum" cosa vogliamo fare? Vogliamo includerli o deprecarli?

**Comment by Mte90** [comment]
Non abbiamo un comando progetti, con i link ai repo su github? possiamo metterlo li e semplificare.

**Comment by dag7dev** [comment]
> possiamo metterlo li e semplificare.

Nessuno lo vedrebbe però. Sono più dell'opinione di lasciarlo come bottone a sé stante nella pulsantiera...

**Comment by Mte90** [comment]
Per me una soluzione vale l'altra, l'importante è che ci sia

**Comment by dag7dev** [comment]
Finalmente si può chiudere questa issue!

Grazie a chi ha contribuito! Che bel traguardo per la nostra community! :tada: :tada: :tada:
